version: '3.1'

services:
  db:
    image: postgres:13
    container_name: odoo-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

  odoo:
    image: odoo:17
    container_name: odoo-app
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    environment:
      - HOST=${ODOO_DB_HOST}
      - USER=${ODOO_DB_USER}
      - PASSWORD=${ODOO_DB_PASSWORD}
    volumes:
      - odoo-web-data:/var/lib/odoo
    restart: always

volumes:
  odoo-db-data:
  odoo-web-data:
